FROM cr.imroc.cc/library/net-tools:latest

RUN cd /tmp && wget https://github.com/etcd-io/etcd/releases/download/v3.5.0/etcd-v3.5.0-linux-amd64.tar.gz &&\
      mv etcd-v3.5.0-linux-amd64/etcdctl /usr/local/bin/